# Ticket to Ride Europe - Game Data
# All cities, routes, and destination tickets

# Scoring table: route length -> points
SCORING = {
    1: 1,
    2: 2,
    3: 4,
    4: 7,
    6: 15,
    8: 21,
}

# Cities with pixel coordinates on the 1200x819 map image
# These map directly to the SVG viewBox "0 0 1200 819"
CITIES = {
    "Edinburgh":        {"x": 150,  "y": 40},
    "London":           {"x": 218,  "y": 190},
    "Amsterdam":        {"x": 290,  "y": 152},
    "Bruxelles":        {"x": 265,  "y": 205},
    "Dieppe":           {"x": 212,  "y": 260},
    "Brest":            {"x": 105,  "y": 290},
    "Paris":            {"x": 250,  "y": 305},
    "Pamplona":         {"x": 200,  "y": 440},
    "Madrid":           {"x": 130,  "y": 520},
    "Lisboa":           {"x": 62,   "y": 575},
    "Cadiz":            {"x": 98,   "y": 650},
    "Barcelona":        {"x": 250,  "y": 510},
    "Marseille":        {"x": 335,  "y": 470},
    "Zurich":           {"x": 375,  "y": 335},
    "Munchen":          {"x": 455,  "y": 285},
    "Frankfurt":        {"x": 400,  "y": 248},
    "Essen":            {"x": 388,  "y": 175},
    "Berlin":           {"x": 498,  "y": 162},
    "Kobenhavn":        {"x": 495,  "y": 75},
    "Stockholm":        {"x": 535,  "y": 32},
    "Danzig":           {"x": 568,  "y": 125},
    "Warszawa":         {"x": 640,  "y": 198},
    "Wien":             {"x": 540,  "y": 278},
    "Venezia":          {"x": 412,  "y": 375},
    "Roma":             {"x": 425,  "y": 488},
    "Palermo":          {"x": 412,  "y": 655},
    "Brindisi":         {"x": 545,  "y": 503},
    "Athina":           {"x": 640,  "y": 598},
    "Zagrab":           {"x": 520,  "y": 380},
    "Sarajevo":         {"x": 568,  "y": 435},
    "Sofia":            {"x": 685,  "y": 465},
    "Bucuresti":        {"x": 750,  "y": 410},
    "Budapest":         {"x": 628,  "y": 302},
    "Kyiv":             {"x": 802,  "y": 222},
    "Wilno":            {"x": 725,  "y": 142},
    "Smolensk":         {"x": 850,  "y": 145},
    "Moskva":           {"x": 960,  "y": 96},
    "Petrograd":        {"x": 942,  "y": 30},
    "Riga":             {"x": 718,  "y": 62},
    "Kharkov":          {"x": 940,  "y": 182},
    "Rostov":           {"x": 1012, "y": 260},
    "Sevastopol":       {"x": 892,  "y": 405},
    "Sochi":            {"x": 1015, "y": 368},
    "Erzurum":          {"x": 1050, "y": 458},
    "Angora":           {"x": 978,  "y": 588},
    "Smyrna":           {"x": 845,  "y": 602},
    "Constantinople":   {"x": 870,  "y": 498},
}

# Routes: (city_a, city_b, length, color, is_tunnel, ferry_locos)
# color: "gray" means any color can be used
# ferry_locos: number of locomotive cards required (0 = not a ferry)
ROUTES = [
    # Iberian Peninsula & Western France
    ("Lisboa", "Cadiz", 2, "blue", False, 0),
    ("Madrid", "Lisboa", 3, "pink", False, 0),
    ("Madrid", "Cadiz", 3, "orange", False, 0),
    ("Madrid", "Pamplona", 3, "black", True, 0),
    ("Madrid", "Pamplona", 3, "white", True, 0),
    ("Madrid", "Barcelona", 2, "yellow", False, 0),
    ("Pamplona", "Barcelona", 2, "gray", True, 0),
    ("Barcelona", "Marseille", 4, "gray", False, 0),
    ("Pamplona", "Marseille", 4, "red", False, 0),
    ("Brest", "Pamplona", 4, "pink", False, 0),

    # France & Low Countries
    ("Pamplona", "Paris", 4, "blue", False, 0),
    ("Pamplona", "Paris", 4, "green", False, 0),
    ("Paris", "Marseille", 4, "gray", False, 0),
    ("Paris", "Brest", 3, "black", False, 0),
    ("Paris", "Dieppe", 1, "pink", False, 0),
    ("Paris", "Zurich", 3, "gray", True, 0),
    ("Paris", "Frankfurt", 3, "white", False, 0),
    ("Paris", "Frankfurt", 3, "orange", False, 0),
    ("Paris", "Bruxelles", 2, "yellow", False, 0),
    ("Paris", "Bruxelles", 2, "red", False, 0),
    ("Dieppe", "Brest", 2, "orange", False, 0),
    ("Dieppe", "Bruxelles", 2, "green", False, 0),
    ("Bruxelles", "Amsterdam", 1, "black", False, 0),
    ("Bruxelles", "Frankfurt", 2, "blue", False, 0),
    ("Amsterdam", "Frankfurt", 2, "white", False, 0),
    ("Amsterdam", "Essen", 3, "yellow", False, 0),

    # English Channel & British Isles
    ("Dieppe", "London", 2, "gray", False, 1),
    ("Dieppe", "London", 2, "gray", False, 1),
    ("Amsterdam", "London", 2, "gray", False, 2),
    ("Edinburgh", "London", 4, "black", False, 0),
    ("Edinburgh", "London", 4, "orange", False, 0),

    # Switzerland, Germany & Austria
    ("Zurich", "Marseille", 2, "pink", True, 0),
    ("Zurich", "Venezia", 2, "green", True, 0),
    ("Zurich", "Munchen", 2, "yellow", True, 0),
    ("Marseille", "Roma", 4, "gray", True, 0),
    ("Munchen", "Venezia", 2, "blue", True, 0),
    ("Munchen", "Frankfurt", 2, "pink", False, 0),
    ("Munchen", "Wien", 3, "orange", False, 0),
    ("Frankfurt", "Essen", 2, "green", False, 0),
    ("Frankfurt", "Berlin", 3, "black", False, 0),
    ("Frankfurt", "Berlin", 3, "red", False, 0),
    ("Essen", "Berlin", 2, "blue", False, 0),
    ("Berlin", "Wien", 3, "green", False, 0),

    # Scandinavia & Baltic
    ("Essen", "Kobenhavn", 3, "gray", False, 1),
    ("Essen", "Kobenhavn", 3, "gray", False, 1),
    ("Kobenhavn", "Stockholm", 3, "yellow", False, 0),
    ("Kobenhavn", "Stockholm", 3, "white", False, 0),
    ("Stockholm", "Petrograd", 8, "gray", True, 0),
    ("Petrograd", "Riga", 4, "gray", False, 0),
    ("Petrograd", "Wilno", 4, "blue", False, 0),
    ("Petrograd", "Moskva", 4, "white", False, 0),
    ("Riga", "Wilno", 4, "green", False, 0),
    ("Riga", "Danzig", 3, "black", False, 0),
    ("Danzig", "Berlin", 4, "gray", False, 0),
    ("Danzig", "Warszawa", 2, "gray", False, 0),

    # Poland & Eastern Europe
    ("Berlin", "Warszawa", 4, "pink", False, 0),
    ("Berlin", "Warszawa", 4, "yellow", False, 0),
    ("Warszawa", "Wien", 4, "blue", False, 0),
    ("Warszawa", "Wilno", 3, "red", False, 0),
    ("Warszawa", "Kyiv", 4, "gray", False, 0),
    ("Kyiv", "Wilno", 2, "gray", False, 0),
    ("Wilno", "Smolensk", 3, "yellow", False, 0),
    ("Smolensk", "Kyiv", 3, "red", False, 0),
    ("Smolensk", "Moskva", 2, "orange", False, 0),

    # Italy & Balkans
    ("Venezia", "Roma", 2, "black", False, 0),
    ("Venezia", "Zagrab", 2, "gray", False, 0),
    ("Roma", "Brindisi", 2, "white", False, 0),
    ("Roma", "Palermo", 4, "gray", False, 1),
    ("Brindisi", "Palermo", 3, "gray", False, 1),
    ("Wien", "Zagrab", 2, "gray", False, 0),
    ("Wien", "Budapest", 1, "red", False, 0),
    ("Wien", "Budapest", 1, "white", False, 0),
    ("Zagrab", "Budapest", 2, "orange", False, 0),
    ("Zagrab", "Sarajevo", 3, "red", False, 0),
    ("Budapest", "Sarajevo", 3, "pink", False, 0),
    ("Sarajevo", "Athina", 4, "green", False, 0),
    ("Sarajevo", "Sofia", 2, "gray", True, 0),
    ("Sofia", "Athina", 3, "pink", False, 0),
    ("Sofia", "Constantinople", 3, "blue", False, 0),
    ("Sofia", "Bucuresti", 2, "gray", True, 0),

    # Eastern Mediterranean & Turkey
    ("Brindisi", "Athina", 4, "gray", False, 1),
    ("Athina", "Smyrna", 2, "gray", False, 1),
    ("Palermo", "Smyrna", 6, "gray", False, 2),
    ("Constantinople", "Smyrna", 2, "gray", True, 0),
    ("Constantinople", "Bucuresti", 3, "yellow", False, 0),
    ("Constantinople", "Angora", 2, "gray", True, 0),
    ("Angora", "Smyrna", 3, "orange", True, 0),
    ("Angora", "Erzurum", 3, "black", False, 0),

    # Romania, Ukraine & Russia
    ("Bucuresti", "Budapest", 4, "gray", True, 0),
    ("Bucuresti", "Kyiv", 4, "gray", False, 0),
    ("Bucuresti", "Sevastopol", 4, "white", False, 0),
    ("Budapest", "Kyiv", 6, "gray", True, 0),
    ("Kyiv", "Kharkov", 4, "gray", False, 0),
    ("Kharkov", "Moskva", 4, "gray", False, 0),
    ("Kharkov", "Rostov", 2, "green", False, 0),
    ("Rostov", "Sevastopol", 4, "gray", False, 0),
    ("Rostov", "Sochi", 2, "gray", False, 0),

    # Black Sea & Caucasus
    ("Sevastopol", "Constantinople", 4, "gray", False, 2),
    ("Sevastopol", "Erzurum", 4, "gray", False, 2),
    ("Sevastopol", "Sochi", 2, "gray", False, 1),
    ("Sochi", "Erzurum", 3, "red", True, 0),

    # Additional Mediterranean
    ("Palermo", "Athina", 6, "gray", False, 2),
]

# Destination tickets: (city_a, city_b, points, is_long_route)
TICKETS = [
    # Long routes (6 cards)
    ("Palermo", "Moskva", 20, True),
    ("Brest", "Petrograd", 20, True),
    ("Lisboa", "Danzig", 20, True),
    ("Edinburgh", "Athina", 21, True),
    ("Cadiz", "Stockholm", 21, True),
    ("Kobenhavn", "Erzurum", 21, True),

    # Short routes (40 cards)
    ("Athina", "Angora", 5, False),
    ("Sofia", "Smyrna", 5, False),
    ("Frankfurt", "Kobenhavn", 5, False),
    ("Budapest", "Sofia", 5, False),
    ("Rostov", "Erzurum", 5, False),
    ("Warszawa", "Smolensk", 6, False),
    ("Zurich", "Brindisi", 6, False),
    ("Zagrab", "Brindisi", 6, False),
    ("Kyiv", "Petrograd", 6, False),
    ("Zurich", "Budapest", 6, False),
    ("Paris", "Zagrab", 7, False),
    ("Amsterdam", "Pamplona", 7, False),
    ("London", "Berlin", 7, False),
    ("Brest", "Marseille", 7, False),
    ("Edinburgh", "Paris", 7, False),
    ("Roma", "Smyrna", 8, False),
    ("Madrid", "Zurich", 8, False),
    ("Paris", "Wien", 8, False),
    ("Brest", "Venezia", 8, False),
    ("Palermo", "Constantinople", 8, False),
    ("Madrid", "Dieppe", 8, False),
    ("Berlin", "Bucuresti", 8, False),
    ("Barcelona", "Bruxelles", 8, False),
    ("Marseille", "Essen", 8, False),
    ("Smolensk", "Rostov", 8, False),
    ("Barcelona", "Munchen", 8, False),
    ("Sarajevo", "Sevastopol", 8, False),
    ("Kyiv", "Sochi", 8, False),
    ("Berlin", "Roma", 9, False),
    ("Bruxelles", "Danzig", 9, False),
    ("Venezia", "Constantinople", 10, False),
    ("London", "Wien", 10, False),
    ("Angora", "Kharkov", 10, False),
    ("Essen", "Kyiv", 10, False),
    ("Riga", "Bucuresti", 10, False),
    ("Stockholm", "Wien", 10, False),
    ("Athina", "Wilno", 11, False),
    ("Amsterdam", "Wilno", 12, False),
    ("Berlin", "Moskva", 12, False),
    ("Frankfurt", "Smolensk", 13, False),
]
