# Ticket to Ride Europe - Game Data
# All cities, routes, and destination tickets

# Scoring table: route length -> points
SCORING = {
    1: 1,
    2: 2,
    3: 4,
    4: 7,
    6: 15,
    8: 21,
}

# Cities with approximate coordinates (% of map width/height) for SVG overlay
CITIES = {
    "Edinburgh":        {"x": 13.5, "y": 3.0},
    "London":           {"x": 17.5, "y": 22.0},
    "Amsterdam":        {"x": 24.0, "y": 16.0},
    "Bruxelles":        {"x": 21.5, "y": 22.5},
    "Dieppe":           {"x": 17.0, "y": 28.0},
    "Brest":            {"x": 9.0,  "y": 33.0},
    "Paris":            {"x": 20.0, "y": 33.0},
    "Pamplona":         {"x": 16.0, "y": 52.0},
    "Madrid":           {"x": 10.5, "y": 60.5},
    "Lisboa":           {"x": 5.0,  "y": 70.0},
    "Cadiz":            {"x": 8.5,  "y": 80.0},
    "Barcelona":        {"x": 20.5, "y": 62.0},
    "Marseille":        {"x": 28.0, "y": 57.0},
    "Zurich":           {"x": 31.0, "y": 39.0},
    "Munchen":          {"x": 38.0, "y": 32.0},
    "Frankfurt":        {"x": 32.5, "y": 26.0},
    "Essen":            {"x": 30.0, "y": 18.0},
    "Berlin":           {"x": 39.0, "y": 18.0},
    "Kobenhavn":        {"x": 37.0, "y": 6.0},
    "Stockholm":        {"x": 48.0, "y": 3.0},
    "Danzig":           {"x": 48.5, "y": 13.0},
    "Warszawa":         {"x": 54.0, "y": 22.0},
    "Wien":             {"x": 44.5, "y": 31.0},
    "Venezia":          {"x": 35.0, "y": 44.0},
    "Roma":             {"x": 36.0, "y": 57.0},
    "Palermo":          {"x": 37.0, "y": 78.0},
    "Brindisi":         {"x": 46.0, "y": 60.0},
    "Athina":           {"x": 56.0, "y": 72.0},
    "Zagrab":           {"x": 44.0, "y": 44.0},
    "Sarajevo":         {"x": 49.0, "y": 52.0},
    "Sofia":            {"x": 58.0, "y": 55.0},
    "Bucuresti":        {"x": 63.0, "y": 48.0},
    "Budapest":         {"x": 52.0, "y": 35.0},
    "Kyiv":             {"x": 67.0, "y": 26.0},
    "Wilno":            {"x": 62.0, "y": 15.0},
    "Smolensk":         {"x": 72.0, "y": 18.0},
    "Moskva":           {"x": 80.0, "y": 12.0},
    "Petrograd":        {"x": 78.0, "y": 3.0},
    "Riga":             {"x": 60.0, "y": 7.0},
    "Kharkov":          {"x": 78.0, "y": 22.0},
    "Rostov":           {"x": 84.0, "y": 30.0},
    "Sevastopol":       {"x": 74.0, "y": 48.0},
    "Sochi":            {"x": 84.0, "y": 44.0},
    "Erzurum":          {"x": 86.0, "y": 55.0},
    "Angora":           {"x": 80.0, "y": 70.0},
    "Smyrna":           {"x": 70.0, "y": 73.0},
    "Constantinople":   {"x": 72.0, "y": 60.0},
}

# Routes: (city_a, city_b, length, color, is_tunnel, ferry_locos)
# color: "gray" means any color can be used
# ferry_locos: number of locomotive cards required (0 = not a ferry)
ROUTES = [
    # Iberian Peninsula & Western France
    ("Lisboa", "Cadiz", 2, "blue", False, 0),
    ("Madrid", "Lisboa", 3, "pink", False, 0),
    ("Madrid", "Cadiz", 3, "orange", False, 0),
    ("Madrid", "Pamplona", 3, "black", True, 0),
    ("Madrid", "Pamplona", 3, "white", True, 0),
    ("Madrid", "Barcelona", 2, "yellow", False, 0),
    ("Pamplona", "Barcelona", 2, "gray", True, 0),
    ("Barcelona", "Marseille", 4, "gray", False, 0),
    ("Pamplona", "Marseille", 4, "red", False, 0),
    ("Brest", "Pamplona", 4, "pink", False, 0),

    # France & Low Countries
    ("Pamplona", "Paris", 4, "blue", False, 0),
    ("Pamplona", "Paris", 4, "green", False, 0),
    ("Paris", "Marseille", 4, "gray", False, 0),
    ("Paris", "Brest", 3, "black", False, 0),
    ("Paris", "Dieppe", 1, "pink", False, 0),
    ("Paris", "Zurich", 3, "gray", True, 0),
    ("Paris", "Frankfurt", 3, "white", False, 0),
    ("Paris", "Frankfurt", 3, "orange", False, 0),
    ("Paris", "Bruxelles", 2, "yellow", False, 0),
    ("Paris", "Bruxelles", 2, "red", False, 0),
    ("Dieppe", "Brest", 2, "orange", False, 0),
    ("Dieppe", "Bruxelles", 2, "green", False, 0),
    ("Bruxelles", "Amsterdam", 1, "black", False, 0),
    ("Bruxelles", "Frankfurt", 2, "blue", False, 0),
    ("Amsterdam", "Frankfurt", 2, "white", False, 0),
    ("Amsterdam", "Essen", 3, "yellow", False, 0),

    # English Channel & British Isles
    ("Dieppe", "London", 2, "gray", False, 1),
    ("Dieppe", "London", 2, "gray", False, 1),
    ("Amsterdam", "London", 2, "gray", False, 2),
    ("Edinburgh", "London", 4, "black", False, 0),
    ("Edinburgh", "London", 4, "orange", False, 0),

    # Switzerland, Germany & Austria
    ("Zurich", "Marseille", 2, "pink", True, 0),
    ("Zurich", "Venezia", 2, "green", True, 0),
    ("Zurich", "Munchen", 2, "yellow", True, 0),
    ("Marseille", "Roma", 4, "gray", True, 0),
    ("Munchen", "Venezia", 2, "blue", True, 0),
    ("Munchen", "Frankfurt", 2, "pink", False, 0),
    ("Munchen", "Wien", 3, "orange", False, 0),
    ("Frankfurt", "Essen", 2, "green", False, 0),
    ("Frankfurt", "Berlin", 3, "black", False, 0),
    ("Frankfurt", "Berlin", 3, "red", False, 0),
    ("Essen", "Berlin", 2, "blue", False, 0),
    ("Berlin", "Wien", 3, "green", False, 0),

    # Scandinavia & Baltic
    ("Essen", "Kobenhavn", 3, "gray", False, 1),
    ("Essen", "Kobenhavn", 3, "gray", False, 1),
    ("Kobenhavn", "Stockholm", 3, "yellow", False, 0),
    ("Kobenhavn", "Stockholm", 3, "white", False, 0),
    ("Stockholm", "Petrograd", 8, "gray", True, 0),
    ("Petrograd", "Riga", 4, "gray", False, 0),
    ("Petrograd", "Wilno", 4, "blue", False, 0),
    ("Petrograd", "Moskva", 4, "white", False, 0),
    ("Riga", "Wilno", 4, "green", False, 0),
    ("Riga", "Danzig", 3, "black", False, 0),
    ("Danzig", "Berlin", 4, "gray", False, 0),
    ("Danzig", "Warszawa", 2, "gray", False, 0),

    # Poland & Eastern Europe
    ("Berlin", "Warszawa", 4, "pink", False, 0),
    ("Berlin", "Warszawa", 4, "yellow", False, 0),
    ("Warszawa", "Wien", 4, "blue", False, 0),
    ("Warszawa", "Wilno", 3, "red", False, 0),
    ("Warszawa", "Kyiv", 4, "gray", False, 0),
    ("Kyiv", "Wilno", 2, "gray", False, 0),
    ("Wilno", "Smolensk", 3, "yellow", False, 0),
    ("Smolensk", "Kyiv", 3, "red", False, 0),
    ("Smolensk", "Moskva", 2, "orange", False, 0),

    # Italy & Balkans
    ("Venezia", "Roma", 2, "black", False, 0),
    ("Venezia", "Zagrab", 2, "gray", False, 0),
    ("Roma", "Brindisi", 2, "white", False, 0),
    ("Roma", "Palermo", 4, "gray", False, 1),
    ("Brindisi", "Palermo", 3, "gray", False, 1),
    ("Wien", "Zagrab", 2, "gray", False, 0),
    ("Wien", "Budapest", 1, "red", False, 0),
    ("Wien", "Budapest", 1, "white", False, 0),
    ("Zagrab", "Budapest", 2, "orange", False, 0),
    ("Zagrab", "Sarajevo", 3, "red", False, 0),
    ("Budapest", "Sarajevo", 3, "pink", False, 0),
    ("Sarajevo", "Athina", 4, "green", False, 0),
    ("Sarajevo", "Sofia", 2, "gray", True, 0),
    ("Sofia", "Athina", 3, "pink", False, 0),
    ("Sofia", "Constantinople", 3, "blue", False, 0),
    ("Sofia", "Bucuresti", 2, "gray", True, 0),

    # Eastern Mediterranean & Turkey
    ("Brindisi", "Athina", 4, "gray", False, 1),
    ("Athina", "Smyrna", 2, "gray", False, 1),
    ("Palermo", "Smyrna", 6, "gray", False, 2),
    ("Constantinople", "Smyrna", 2, "gray", True, 0),
    ("Constantinople", "Bucuresti", 3, "yellow", False, 0),
    ("Constantinople", "Angora", 2, "gray", True, 0),
    ("Angora", "Smyrna", 3, "orange", True, 0),
    ("Angora", "Erzurum", 3, "black", False, 0),

    # Romania, Ukraine & Russia
    ("Bucuresti", "Budapest", 4, "gray", True, 0),
    ("Bucuresti", "Kyiv", 4, "gray", False, 0),
    ("Bucuresti", "Sevastopol", 4, "white", False, 0),
    ("Budapest", "Kyiv", 6, "gray", True, 0),
    ("Kyiv", "Kharkov", 4, "gray", False, 0),
    ("Kharkov", "Moskva", 4, "gray", False, 0),
    ("Kharkov", "Rostov", 2, "green", False, 0),
    ("Rostov", "Sevastopol", 4, "gray", False, 0),
    ("Rostov", "Sochi", 2, "gray", False, 0),

    # Black Sea & Caucasus
    ("Sevastopol", "Constantinople", 4, "gray", False, 2),
    ("Sevastopol", "Erzurum", 4, "gray", False, 2),
    ("Sevastopol", "Sochi", 2, "gray", False, 1),
    ("Sochi", "Erzurum", 3, "red", True, 0),

    # Additional Mediterranean
    ("Palermo", "Athina", 6, "gray", False, 2),
]

# Destination tickets: (city_a, city_b, points, is_long_route)
TICKETS = [
    # Long routes (6 cards)
    ("Palermo", "Moskva", 20, True),
    ("Brest", "Petrograd", 20, True),
    ("Lisboa", "Danzig", 20, True),
    ("Edinburgh", "Athina", 21, True),
    ("Cadiz", "Stockholm", 21, True),
    ("Kobenhavn", "Erzurum", 21, True),

    # Short routes (40 cards)
    ("Athina", "Angora", 5, False),
    ("Sofia", "Smyrna", 5, False),
    ("Frankfurt", "Kobenhavn", 5, False),
    ("Budapest", "Sofia", 5, False),
    ("Rostov", "Erzurum", 5, False),
    ("Warszawa", "Smolensk", 6, False),
    ("Zurich", "Brindisi", 6, False),
    ("Zagrab", "Brindisi", 6, False),
    ("Kyiv", "Petrograd", 6, False),
    ("Zurich", "Budapest", 6, False),
    ("Paris", "Zagrab", 7, False),
    ("Amsterdam", "Pamplona", 7, False),
    ("London", "Berlin", 7, False),
    ("Brest", "Marseille", 7, False),
    ("Edinburgh", "Paris", 7, False),
    ("Roma", "Smyrna", 8, False),
    ("Madrid", "Zurich", 8, False),
    ("Paris", "Wien", 8, False),
    ("Brest", "Venezia", 8, False),
    ("Palermo", "Constantinople", 8, False),
    ("Madrid", "Dieppe", 8, False),
    ("Berlin", "Bucuresti", 8, False),
    ("Barcelona", "Bruxelles", 8, False),
    ("Marseille", "Essen", 8, False),
    ("Smolensk", "Rostov", 8, False),
    ("Barcelona", "Munchen", 8, False),
    ("Sarajevo", "Sevastopol", 8, False),
    ("Kyiv", "Sochi", 8, False),
    ("Berlin", "Roma", 9, False),
    ("Bruxelles", "Danzig", 9, False),
    ("Venezia", "Constantinople", 10, False),
    ("London", "Wien", 10, False),
    ("Angora", "Kharkov", 10, False),
    ("Essen", "Kyiv", 10, False),
    ("Riga", "Bucuresti", 10, False),
    ("Stockholm", "Wien", 10, False),
    ("Athina", "Wilno", 11, False),
    ("Amsterdam", "Wilno", 12, False),
    ("Berlin", "Moskva", 12, False),
    ("Frankfurt", "Smolensk", 13, False),
]
